const R2 = 'https://pub-d2aef463d8a6497d90ac252cbcb0dcbf.r2.dev'

export type TeamBg = 'orange' | 'yellow' | 'red'

export const TEAM = [
  {
    name: 'Sarah White',
    role: 'GM, African Bitcoiners',
    image: `${R2}/uploads/2024/03/African-Bitcoiners_Meet_the_team_Sarah-White.png`,
    imageW: 673,
    imageH: 673,
    bg: 'orange' as TeamBg,
    xUrl: 'https://x.com/IamWhiteSarah',
  },
  {
    name: 'EM',
    role: 'Head of Tech',
    image: `${R2}/uploads/2024/03/African-Bitcoiners_Meet_the_team_EM.png`,
    imageW: 460,
    imageH: 460,
    bg: 'yellow' as TeamBg,
    xUrl: 'https://x.com/EMbits',
  },
  {
    name: 'Megasley',
    role: 'GM, Africa Free Routing',
    image: `${R2}/uploads/2024/03/African-Bitcoiners_Meet_the_team_Megasley.png`,
    imageW: 239,
    imageH: 239,
    bg: 'orange' as TeamBg,
    xUrl: 'https://x.com/megasley',
  },
  {
    name: 'Satoshee',
    role: 'Designer',
    image: `${R2}/uploads/2025/01/African-Bitcoiners_Meet_the_team_Satoshee.png`,
    imageW: 195,
    imageH: 195,
    bg: 'yellow' as TeamBg,
    xUrl: 'https://x.com/_Satoshee',
    imageScale: '90' as const,
    framePadTop: true,
    socialPadTop: true,
  },
  {
    name: 'Lys',
    role: 'Backend Engineer & Francophone Lead',
    image: `${R2}/uploads/2025/01/African-Bitcoiners-Graduate-Program_Lys-1024x1024.png`,
    imageW: 1024,
    imageH: 1024,
    bg: 'yellow' as TeamBg,
    xUrl: 'https://x.com/ladyyyy_lo?s=21',
    imageScale: '90' as const,
    framePadTop: true,
  },
  {
    name: 'TheOrangeMan',
    role: 'Graduate Program',
    image: `${R2}/uploads/2026/04/Orangeman_profile-removebg-preview.png`,
    imageW: 458,
    imageH: 545,
    bg: 'orange' as TeamBg,
    xUrl: 'https://x.com/JJ_the_creator',
    imageScale: '84' as const,
    imageCorner: true,
    socialPadTop: true,
  },
  {
    name: 'Blcvkman',
    role: 'Graduate Program',
    image: `${R2}/uploads/2026/03/black_man-removebg-preview.png`,
    imageW: 500,
    imageH: 500,
    bg: 'yellow' as TeamBg,
    xUrl: 'https://x.com/blcvkman?s=21',
    imageScale: '90' as const,
    framePadTop: true,
  },
  {
    name: 'Afriqualia',
    role: 'Founder and Catalyst',
    image: `${R2}/uploads/2024/08/Afriqualia_African-Bitcoiners.png`,
    imageW: 500,
    imageH: 500,
    bg: 'red' as TeamBg,
    xUrl: 'https://x.com/afriqualia',
    imageCorner: true,
  },
] as const

export const JOIN_HREF = '/earn-bitcoin/bitcoiner-jobs/graduate-program/'
