import Image from 'next/image'
import Link from 'next/link'
import React from 'react'

import { CourseModalBlockComponent } from '@/blocks/CourseModal/Component'
import { BORDER_STEPS, IMG, LINKS, MEMORIZE_CARDS, SONG_STEPS } from '@/components/KeepBitcoinPage/data'
import { BreakdownIcon, SeedIcon, StoryIcon, WalletIcon } from '@/components/KeepBitcoinPage/icons'
import { GraduateProgramForm } from '@/components/forms/GraduateProgramForm'

const CREAM = '#FEF6EC'
const CREAM_LIGHT = '#FFFBF7'
const ORANGE = '#E1640C'
const ORANGE_LINK = '#F45341'
const TEXT = '#384958'
const HEADING = '#37312C'

const ICONS = {
  wallet: WalletIcon,
  seed: SeedIcon,
  breakdown: BreakdownIcon,
  story: StoryIcon,
}

function Section({
  bg = 'white',
  className = '',
  children,
}: {
  bg?: 'white' | 'cream' | 'cream-light'
  className?: string
  children: React.ReactNode
}) {
  const bgColor = bg === 'cream' ? CREAM : bg === 'cream-light' ? CREAM_LIGHT : '#FFFFFF'
  return (
    <section className={`px-4 py-10 sm:px-6 md:py-14 ${className}`} style={{ backgroundColor: bgColor }}>
      {children}
    </section>
  )
}

function OrangeLink({ href, children, external, centered }: { href: string; children: React.ReactNode; external?: boolean; centered?: boolean }) {
  const className = `inline-flex items-center gap-2 text-base font-semibold transition-opacity hover:opacity-80 ${centered ? 'mx-auto' : ''}`
  const style = { color: ORANGE_LINK }
  const icon = (
    <svg viewBox="0 0 16 16" fill="currentColor" className="h-3.5 w-3.5" aria-hidden>
      <path d="M3 8h9M9 5l3 3-3 3" stroke="currentColor" strokeWidth="1.5" fill="none" strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  )
  if (external) {
    return (
      <a href={href} target="_blank" rel="noopener noreferrer" className={className} style={style}>
        {children}
        {icon}
      </a>
    )
  }
  return (
    <Link href={href} className={className} style={style}>
      {children}
      {icon}
    </Link>
  )
}

function MemorizeCard({
  icon,
  title,
  description,
  button,
}: {
  icon: keyof typeof ICONS
  title: string
  description: string
  button?: { label: string; href: string }
}) {
  const Icon = ICONS[icon]
  return (
    <article className="flex h-full flex-col px-2 py-4 sm:px-4">
      <div className="flex justify-center">
        <Icon />
      </div>
      <h3 className="mt-5 text-center font-heading text-xl font-bold sm:text-[22px]" style={{ color: HEADING }}>
        {title}
      </h3>
      <p className="mt-4 flex-1 text-center text-base leading-7 tracking-[-0.4px] sm:text-left" style={{ color: TEXT }}>
        {description}
      </p>
      {button && (
        <div className="mt-6 flex justify-center">
          <OrangeLink href={button.href} centered>
            {button.label}
          </OrangeLink>
        </div>
      )}
    </article>
  )
}

function StepCard({ num, title, body }: { num: number; title: string; body: string }) {
  return (
    <div className="rounded-[7px] bg-white p-7 shadow-[0_6px_16px_rgba(16,25,40,0.08)] sm:px-7 sm:py-10">
      <h5 className="font-heading text-lg font-bold" style={{ color: HEADING }}>
        {num}. {title}
      </h5>
      <p className="mt-3 whitespace-pre-line text-base leading-7" style={{ color: TEXT }}>
        {body}
      </p>
    </div>
  )
}

export function KeepBitcoinPage() {
  return (
    <div className="overflow-x-hidden bg-white font-sans">
      {/* Hero */}
      <Section bg="cream">
        <div className="mx-auto max-w-[900px] text-center">
          <h1 className="font-heading text-3xl font-bold leading-tight sm:text-4xl md:text-[42px] md:leading-[50px]" style={{ color: HEADING }}>
            How To Keep Bitcoin In Your Head
          </h1>
          <p className="mx-auto mt-5 max-w-3xl text-base leading-7 sm:text-[17px] sm:leading-[30px]" style={{ color: TEXT }}>
            It is vital to secure your Bitcoin. One of the most secure ways to do this is by storing your Bitcoin in a
            wallet that utilizes a 12 or 24 word seed phrase. This ensures that the private key generated by the wallet
            are stored as a list of words which are easily understandable and can be memorized easily. Writing down your
            seed phrase on paper or storing it on your computer leaves it vulnerable to theft or loss. That&apos;s why
            memorization is a valuable step in securing your Bitcoin.
          </p>
        </div>
      </Section>

      {/* Memorizing grid */}
      <Section bg="white">
        <div className="mx-auto max-w-[1200px]">
          <h2 className="text-center font-heading text-2xl font-bold sm:text-[28px]" style={{ color: HEADING }}>
            Memorizing Your Seed Phrase
          </h2>
          <div className="mt-10 grid grid-cols-1 gap-8 md:grid-cols-2 md:gap-x-10 md:gap-y-12">
            {MEMORIZE_CARDS.map((card) => (
              <MemorizeCard key={card.title} {...card} />
            ))}
          </div>
        </div>
      </Section>

      {/* Note + story continuation */}
      <Section bg="cream-light">
        <div className="mx-auto max-w-[1200px]">
          <div className="grid grid-cols-1 items-center gap-8 md:grid-cols-2 md:gap-12">
            <div>
              <h4 className="font-heading text-2xl font-bold sm:text-[28px]" style={{ color: HEADING }}>
                Note
              </h4>
              <p className="mt-4 text-base leading-7" style={{ color: TEXT }}>
                <strong>I</strong>t&apos;s crucial to remember the order of the words in each group. If you remember the
                words but not their correct order, you won&apos;t be able to access your Bitcoin. Here is an example of a
                story for that seed phrase. Often the more silly stories are easier to remember. The ORANGE BANANA shaped
                DOG hunted furiously on the ground. He was looking for an APPLE to throw at the MONKEY in the SKY, which
                was annoying.
              </p>
            </div>
            <div className="flex justify-center md:justify-end">
              <div className="overflow-hidden rounded-full">
                <Image src={IMG.note} alt="" width={400} height={400} className="h-auto w-full max-w-[280px] object-cover sm:max-w-[320px]" />
              </div>
            </div>
          </div>

          <div className="mx-auto mt-8 max-w-[900px] space-y-4 text-base leading-7" style={{ color: TEXT }}>
            <p>
              Our poor furry friend was thirsty. He wanted some PLAIN WATER and a little bit of PIZZA. He knew with this
              in belly he could visit his old friend the ELEPHANT and together they could use the BEAUTIFUL money, Bitcoin,
              to INVOKE a world of Freedom.
            </p>
            <p>
              By creating these vivid and unusual images, you can easily remember each group of words in the right order.
              And if you need to recall your seed phrase in the future, you can simply think back to the stories and images
              you created, making it easier to remember and access your Bitcoin.
            </p>
          </div>
        </div>
      </Section>

      {/* Practice */}
      <Section bg="cream-light">
        <div className="mx-auto grid max-w-[1200px] grid-cols-1 items-center gap-8 md:grid-cols-2 md:gap-12">
          <div className="order-2 flex justify-center md:order-1 md:justify-start">
            <Image
              src={IMG.practice}
              alt="Practice memorizing your seed phrase"
              width={600}
              height={600}
              className="h-auto w-full max-w-[380px] object-contain"
              sizes="(max-width: 768px) 100vw, 380px"
            />
          </div>
          <div className="order-1 md:order-2">
            <h4 className="font-heading text-2xl font-bold sm:text-[28px]" style={{ color: HEADING }}>
              Practice Memorizing Your Seed Phrase
            </h4>
            <p className="mt-4 text-base leading-7" style={{ color: TEXT }}>
              To ensure that you can remember your seed phrase easily, it&apos;s important to practice recalling it
              regularly. You can do this by reciting it aloud or writing it down from memory. When practicing your
              story, try clapping on each seed word. This will help you brain remember which words in the story are the
              seed words. For instance, if your seed phrase is{' '}
              <strong>
                <em>orange banana dog apple monkey sky plain water pizza elephant beautiful invoke,</em>
              </strong>{' '}
              you can use the phrase{' '}
              <em>
                <strong>Oliver&apos;s Big Ducks Always Make Silly Pizzas; Wearing Pink Elephants&apos; Boots Indoors</strong>
              </em>{' '}
              as a mnemonic device. By linking the first letters of each word with a memorable phrase, you can enhance
              your recall and keep your seed phrase secure.
            </p>
          </div>
        </div>
      </Section>

      {/* Song section */}
      <Section bg="white">
        <div className="mx-auto max-w-[1200px]">
          <div className="grid grid-cols-1 items-start gap-6 md:grid-cols-[1fr_auto] md:gap-8">
            <h4 className="font-heading text-2xl font-bold sm:text-[28px]" style={{ color: HEADING }}>
              Creating a Song from Your Seed Phrase Word Groups
            </h4>
            <div className="flex justify-center md:justify-end">
              <Image src={IMG.song} alt="" width={280} height={260} className="h-auto w-full max-w-[200px] object-contain sm:max-w-[240px]" />
            </div>
          </div>

          <div className="relative mt-12 hidden lg:block">
            <div className="grid grid-cols-[1fr_120px_1fr] gap-4">
              <div className="space-y-[88px]">
                <StepCard {...SONG_STEPS[0]} />
                <StepCard {...SONG_STEPS[2]} />
              </div>
              <div className="relative">
                <Image src={IMG.arrow12} alt="" width={177} height={164} className="absolute left-1/2 top-[72px] w-[110px] -translate-x-1/2" />
                <Image src={IMG.arrow12} alt="" width={177} height={164} className="absolute bottom-[88px] left-1/2 w-[110px] -translate-x-1/2 scale-x-[-1]" />
                <Image src={IMG.arrow34} alt="" width={175} height={165} className="absolute left-1/2 top-[48%] w-[110px] -translate-x-1/2 -translate-y-1/2" />
              </div>
              <div className="space-y-[88px] pt-[88px]">
                <StepCard {...SONG_STEPS[1]} />
                <StepCard {...SONG_STEPS[3]} />
              </div>
            </div>
          </div>

          <div className="mt-8 grid grid-cols-1 gap-5 lg:hidden">
            {SONG_STEPS.map((step) => (
              <StepCard key={step.num} {...step} />
            ))}
          </div>
        </div>
      </Section>

      {/* Border Wallets */}
      <Section bg="cream">
        <div className="mx-auto max-w-[1200px]">
          <div className="grid grid-cols-1 items-start gap-8 md:grid-cols-2 md:gap-12">
            <div>
              <h4 className="font-heading text-2xl font-bold sm:text-[28px]" style={{ color: HEADING }}>
                Border Wallets
              </h4>
              <div className="mt-4 space-y-4 text-base leading-7" style={{ color: TEXT }}>
                <p>
                  Border Wallet is a new technology that makes memorizing seed phrases easy. This Bitcoin wallet utilizes
                  pattern recognition to help you remember a seed phrase easily, securely, and reliably. The concept draws
                  on the Picture Superiority Effect and uses user-generated patterns applied to a randomized map of seed
                  words, offline and in a secure air-gapped setting. By drawing a pattern on words, you create the first 11
                  or 23 words of your seed phrase.
                </p>
                <p>
                  You can create your Border wallet by following the official{' '}
                  <a href={LINKS.borderGuide} target="_blank" rel="noopener noreferrer" className="font-semibold hover:underline" style={{ color: ORANGE }}>
                    Border Wallet guide
                  </a>{' '}
                  or on{' '}
                  <a href={LINKS.sparrow} target="_blank" rel="noopener noreferrer" className="font-semibold hover:underline" style={{ color: ORANGE }}>
                    Sparrow Wallet
                  </a>
                  .
                </p>
                <p>
                  <strong>To create a border wallet on Sparrow Wallet, follow these steps:</strong>
                </p>
              </div>
            </div>
            <div className="flex justify-center md:justify-end">
              <Image
                src={IMG.borderWallet}
                alt="Border wallet grid"
                width={500}
                height={500}
                className="h-auto w-full max-w-[380px] object-contain"
                sizes="(max-width: 768px) 100vw, 380px"
              />
            </div>
          </div>

          <ol className="mx-auto mt-8 max-w-[900px] list-decimal space-y-3 pl-5 text-base leading-7" style={{ color: TEXT }}>
            {BORDER_STEPS.map((step) => (
              <li key={step}>{step}</li>
            ))}
          </ol>
          <div className="mx-auto mt-8 max-w-[900px]">
            <a
              href={LINKS.borderVideo}
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex border px-10 py-[15px] text-[17px] font-bold tracking-[-0.4px] transition-colors hover:bg-white"
              style={{ borderColor: ORANGE, color: ORANGE }}
            >
              Comprehensive Guide to Creating a Border Wallet
            </a>
          </div>
        </div>
      </Section>

      {/* Passphrase */}
      <Section bg="cream">
        <div className="mx-auto grid max-w-[1200px] grid-cols-1 items-center gap-8 md:grid-cols-2 md:gap-12">
          <div className="flex justify-center md:justify-start">
            <Image
              src={IMG.passphrase}
              alt="Passphrase security illustration"
              width={500}
              height={500}
              className="h-auto w-full max-w-[320px] object-contain"
              sizes="(max-width: 768px) 100vw, 320px"
            />
          </div>
          <div>
            <h4 className="font-heading text-2xl font-bold sm:text-[28px]" style={{ color: HEADING }}>
              Passphrase
            </h4>
            <div className="mt-4 space-y-4 text-base leading-7" style={{ color: TEXT }}>
              <p>
                Adding a passphrase to your seed phrase is valuable for securing your Bitcoin wallet. A passphrase is an
                additional layer of security that is used to encrypt your seed phrase and make it even more difficult for
                unauthorized users to access your wallet.
              </p>
              <p>
                If your seed phrase falls into the wrong hands, anyone can gain access to your Bitcoin wallet and steal
                your funds. However, if you have added a passphrase to your seed phrase, the thief will also need to know
                the passphrase to access your wallet. This makes it much more difficult for anyone to steal your Bitcoin.
              </p>
            </div>
          </div>
        </div>
      </Section>

      {/* Summary */}
      <Section bg="cream">
        <div className="mx-auto max-w-[900px]">
          <h4 className="font-heading text-2xl font-bold sm:text-[28px]" style={{ color: HEADING }}>
            Summary
          </h4>
          <div className="mt-4 space-y-4 text-base leading-7" style={{ color: TEXT }}>
            <p>
              While it&apos;s valuable to memorize your seed phrase and passphrase, it&apos;s okay to write them down as
              long as you store them separately. It&apos;s crucial never to write down your seed phrase and passphrase
              together. This is because if someone gains access to both, they can easily access your Bitcoin wallet and
              steal your funds.
            </p>
            <p>
              Ultimately, the security of your Bitcoin wallet depends on how well you protect your seed phrase and
              passphrase. Be sure to take the necessary steps to keep them safe and secure at all times, including
              memorizing both or, keeping them separate in secure locations. Learn more about Bitcoin{' '}
              <Link href={LINKS.security} className="font-semibold hover:underline" style={{ color: ORANGE }}>
                security here.
              </Link>
            </p>
          </div>
        </div>
      </Section>

      {/* Course signup */}
      <Section bg="cream">
        <div className="mx-auto max-w-[900px] rounded-[7px] border border-[#603913]/10 bg-white px-5 py-10 shadow-[0_6px_16px_rgba(16,25,40,0.08)] sm:px-8 sm:py-12 md:px-12">
          <h4 className="text-center font-heading text-lg font-bold leading-snug tracking-[-0.5px] sm:text-xl md:text-2xl">
            <span style={{ color: HEADING }}>
              To learn more about Bitcoin wallets and how to setup one, Sign up to take our Bitcoin for Beginners Course for{' '}
            </span>
            <span style={{ color: ORANGE }}>free</span>
          </h4>
          <div className="mt-8">
            <CourseModalBlockComponent
              triggerLabel="Get Started"
              variant="primary-orange"
              layout="inline"
              websiteUrl="https://course.bitcoiners.africa"
              fullWidth
            />
          </div>
        </div>
      </Section>

      {/* Graduate program */}
      <Section bg="white" className="pb-16 md:pb-24">
        <div className="mx-auto max-w-[800px]">
          <h4 className="mb-8 font-heading text-2xl font-bold sm:text-[28px]" style={{ color: HEADING }}>
            Apply to the African Bitcoiners Graduate Program
          </h4>
          <div className="rounded-[7px] border border-[#EAECF0] bg-white p-6 shadow-[0_6px_16px_rgba(16,25,40,0.06)] sm:p-8">
            <GraduateProgramForm />
          </div>
        </div>
      </Section>
    </div>
  )
}
