const R2 = 'https://pub-d2aef463d8a6497d90ac252cbcb0dcbf.r2.dev'

export const IMG = {
  hero: `${R2}/uploads/2025/06/Africa-Bitcoiners-3rd-Anniversary-min.png`,
  testimonialsBg: `${R2}/uploads/2024/01/Proof-of-Work-bg2.png`,
  quoteRight: `${R2}/uploads/2024/01/Right-quote.png`,
  quoteLeft: `${R2}/uploads/2024/01/Left-quote.png`,
  quoteLeft2: `${R2}/uploads/2024/01/Left-quote-2.png`,
  quoteRight2: `${R2}/uploads/2024/01/Right-quote-2.png`,
  communityWatch: `${R2}/uploads/2025/06/millionsats.png`,
  communityBook: `${R2}/uploads/2025/06/group.png`,
  communitySavers: `${R2}/uploads/2025/06/millionsats-1.png`,
} as const

export const PARTNERS = [
  { href: 'https://www.btrust.tech/', src: `${R2}/uploads/2025/06/btrust-1.png`, w: 151, h: 64, alt: 'Btrust' },
  { href: 'https://x.com/OpenSats', src: `${R2}/uploads/2025/06/opensats-22.png`, w: 233, h: 156, alt: 'OpenSats' },
  { href: 'https://www.voltage.cloud/', src: `${R2}/uploads/2025/06/Voltage_Logo_11.png`, w: 182, h: 102, alt: 'Voltage' },
  { href: 'https://tether.to/en/', src: `${R2}/uploads/2025/06/tether.png`, w: 252, h: 55, alt: 'Tether' },
  { href: 'https://hrf.org/', src: `${R2}/uploads/2025/06/human_rights_foundation.png`, w: 203, h: 67, alt: 'Human Rights Foundation' },
  { href: 'https://geyser.fund/', src: `${R2}/uploads/2025/06/geyser-1.png`, w: 224, h: 72, alt: 'Geyser' },
  { href: 'https://academy.trezor.io/', src: `${R2}/uploads/2024/10/Trezor_Academy_Logo_Black.svg`, w: 235, h: 45, alt: 'Trezor Academy' },
  { href: 'https://www.blink.sv/', src: `${R2}/uploads/2025/06/blink_wallet-33.png`, w: 224, h: 128, alt: 'Blink Wallet' },
  { href: 'https://afrobitcoin.org/', src: `${R2}/uploads/2025/06/Africa-Bitcoin-Conference-bgre.png`, w: 220, h: 104, alt: 'Africa Bitcoin Conference' },
  { href: 'https://lightning-roulette.com/', src: `${R2}/uploads/2025/06/lightning-Roulette.png`, w: 92, h: 92, alt: 'Lightning Roulette' },
  { href: 'https://www.fedi.xyz/', src: `${R2}/uploads/2025/06/fedi-1.png`, w: 245, h: 107, alt: 'Fedi' },
  { href: 'https://ipaybtc.app/', src: `${R2}/uploads/2025/06/Ipaybtc-new.png`, w: 217, h: 81, alt: 'iPayBTC' },
  { href: 'https://za25.adoptingbitcoin.org/', src: `${R2}/uploads/2025/06/adopting-Bitcoin-logo.png`, w: 193, h: 115, alt: 'Adopting Bitcoin' },
  { href: 'https://my.cracktheorange.com/', src: `${R2}/uploads/2025/06/crack-the-orange-1.png`, w: 241, h: 79, alt: 'Crack the Orange' },
  { href: 'https://citrusrate.com/', src: `${R2}/uploads/2025/06/Citrusrate-1.png`, w: 128, h: 133, alt: 'Citrusrate' },
  { href: 'https://planb.network/en', src: `${R2}/uploads/2025/06/plan_b_logo-2.png`, w: 151, h: 89, alt: 'Plan B Network' },
  { href: 'https://btcmap.org/', src: `${R2}/uploads/2025/06/btc-map.png`, w: 122, h: 122, alt: 'BTC Map' },
] as const

export const INITIATIVES = [
  {
    title: 'Africa Free Routing',
    icon: `${R2}/uploads/2024/03/African-Bitcoiners_Africa-Free-Routing-Product.png`,
    iconW: 96,
    iconH: 96,
    image: `${R2}/uploads/2025/06/AFRnode.png`,
    imageW: 751,
    imageH: 396,
    body: 'Unlocking possibilities with Africa Free Routing, the largest and most reliable free lightning payments routing network in Africa! Our network stands tall with 5 nodes with 4 of these nodes strategically hosted within the continent, fostering seamless connections between African retailers and customers. With an impressive 233 channels and a total capacity of 920,102,593, we empower businesses and individuals to embrace Bitcoin as a reliable form of payment.',
    href: 'https://freerouting.africa/',
    cta: 'VISIT WEBSITE →',
    external: true,
  },
  {
    title: 'Bitcoin for Beginners Course',
    icon: `${R2}/uploads/2024/03/African-bitcoiners_official_logo.png`,
    iconW: 96,
    iconH: 96,
    image: `${R2}/uploads/2024/03/African-Bitcoiners_Bitcoin-for-Beginners-Course-image.png`,
    imageW: 751,
    imageH: 380,
    body: 'Our FREE Bitcoin for Beginners course has empowered over 533 graduates across Africa. Carefully crafted with simplicity in mind, this course provides a solid foundation for your Bitcoin journey. Dive into the basics with ease through pictorial illustrations. Let\'s learn and grow together!',
    href: '/learn-bitcoin/free-bitcoin-course/',
    cta: 'VISIT PAGE →',
    external: false,
  },
  {
    title: 'Sats2data',
    icon: `${R2}/uploads/2024/03/African-Bitcoiners_Sats2data-logo-white.png`,
    iconW: 96,
    iconH: 96,
    image: `${R2}/uploads/2024/03/African-Bitcoiners_Sats2data-image.png`,
    imageW: 751,
    imageH: 380,
    body: 'Experience seamless airtime and data purchases using Bitcoin in 40 African countries. Sats2data is one of our utility contributions to the African Bitcoin ecosystem, fostering financial inclusivity across the continent. Join us on the journey to a connected and economically empowered Africa with Sats2Data.',
    href: 'https://sats2data.africa/',
    cta: 'VISIT WEBSITE →',
    external: true,
  },
  {
    title: 'The Bitcoiner Test',
    icon: `${R2}/uploads/2024/03/African-Bitcoiners_The-Bitcoiner-Test-Product.png`,
    iconW: 96,
    iconH: 96,
    image: `${R2}/uploads/2024/01/The-Bitcoiner-Test-img-1-e1706247554177.png`,
    imageW: 751,
    imageH: 380,
    body: 'An industry-standard exam has a count of being taken in 21 countries worldwide. Developed, compiled, and audited by Bitcoin experts, it thoroughly assesses job candidates\' knowledge, proving they\'re true Bitcoiners. This test was designed to serve as a tool that can thoroughly access individuals who claim to be Bitcoiners and prove that they know their onions, and also to help Bitcoin firms and organizations test their employees/potential employees and be sure that they\'re hiring real Bitcoiners.',
    href: 'https://bitcoinertest.com/leaderboard/',
    cta: 'VISIT WEBSITE →',
    external: true,
  },
  {
    title: 'Most Impactful African Bitcoiners',
    image: `${R2}/uploads/2024/03/African-Bitcoiners_Most-Impactful-African-Bitcoiners.png`,
    imageW: 751,
    imageH: 380,
    body: 'Garnering a total view of 190000+ on Twitter alone in 2023, our 21 Most Impact African Bitcoiners list is an initiative we started to recognize and honor the dedication of Africans who are actively contributing to the growth and development of Bitcoin within Africa. The overwhelming engagement with this initiative in 2023 by the African Bitcoin community reflects a growing community invested in the work we\'re doing.',
    href: '/the-most-impactful-african-bitcoiners-of-2023/',
    cta: 'VISIT PAGE →',
    external: false,
  },
  {
    title: 'African Bitcoin Ecosystem  Infographic',
    image: `${R2}/uploads/2024/03/African-Bitcoiners_Ecosystem-Infographic-image-1024x519.png`,
    imageW: 1024,
    imageH: 519,
    body: 'We\'ve proactively taken the lead in conducting comprehensive quarterly research on the Bitcoin ecosystem in Africa. Our commitment extends to presenting a visual representation of this research through an insightful infographic. This strategic approach not only facilitates easy access for those seeking information on all Bitcoin-only initiatives in Africa but also allows us to measure our quarterly growth effectively.',
    href: '/african-bitcoin-ecosystem/',
    cta: 'VISIT PAGE →',
    external: false,
  },
  {
    title: 'Lightning Development Bootcamp',
    image: `${R2}/uploads/2025/06/bootcampimage.png`,
    imageW: 751,
    imageH: 380,
    body: 'The Bitcoin Lightning Development Bootcamp Africa, a hands-on training program organized by Africa Free Routing to equip developers with the skills to build on Bitcoin\'s Lightning Network. This immersive bootcamp covers key Lightning concepts, hands-on coding sessions, and real-world applications, empowering participants to contribute to the Bitcoin ecosystem. Whether you\'re new to Lightning development or looking to deepen your expertise, this bootcamp provides the guidance, tools, and community support needed to excel.',
    href: 'https://freerouting.africa/cape-town-lightning-developer-bootcamp/',
    cta: 'VISIT PAGE →',
    external: true,
  },
  {
    title: 'Bitcoin: Africa\'s Guide to  Freedom Money',
    image: `${R2}/uploads/2025/06/starterbook.png`,
    imageW: 751,
    imageH: 380,
    body: 'The first-ever African Bitcoin starter book, written in simple, engaging language with illustrations and local examples. This book is designed to help everyday Africans understand Bitcoin and why it matters. Whether you\'re new or curious, this is your guide to freedom money.',
    href: '/bitcoin-africas-guide-to-freedom-money/',
    cta: 'VISIT PAGE →',
    external: false,
  },
] as const

export const COMMUNITY = [
  {
    title: 'WATCH PARTY',
    description: '30 Sessions Completed',
    bg: IMG.communityWatch,
    icon: 'film' as const,
  },
  {
    title: 'BOOK CLUB',
    description: '30 Sessions Completed',
    bg: IMG.communityBook,
    icon: 'book' as const,
  },
  {
    title: 'MILLION SATS SAVERS',
    description: '465 Bitcoin Savers',
    bg: IMG.communitySavers,
    icon: 'film' as const,
  },
] as const

export const TESTIMONIALS = [
  {
    label: 'COURSE FEEDBACK',
    body: 'I was very pleased with the Bitcoin course that I took. The questions were well-written and covered a wide range of topics related to Bitcoin. I also appreciated the fact that the company is seeking feedback from users.',
    variant: 'green-left' as const,
    quoteTop: IMG.quoteRight,
    quoteBottom: IMG.quoteLeft,
  },
  {
    label: 'WATCH PARTY FEEDBACK',
    body: 'You have the best newsletter look and feel of any of the others I\'ve seen. Loved the watch party this week and hope to make the next one as well. Keep showing folks how its done!',
    variant: 'orange-right' as const,
    quoteTop: IMG.quoteLeft2,
    quoteBottom: IMG.quoteRight2,
  },
  {
    label: 'COURSE FEEDBACK',
    body: 'Wow so interesting bitcoiners Africa may you be blessed with such good program of educate youth more about digital currency especially in bitcoin, I real enjoy the quiz.',
    variant: 'green-left' as const,
    quoteTop: IMG.quoteRight,
    quoteBottom: IMG.quoteLeft,
  },
  {
    label: 'COURSE FEEDBACK',
    body: 'I loved it, most beginner Bitcoin courses are a little shallow and are mostly repetitive. I love the inclusion of the open source contribution, scalability and the transaction lessons. For a Beginner course, it pretty much covers a lot of areas that are omitted in other courses.',
    variant: 'green-right' as const,
    quoteTop: IMG.quoteLeft2,
    quoteBottom: IMG.quoteRight2,
  },
] as const
