/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    media: Media;
    users: User;
    jobs: Job;
    testimonials: Testimonial;
    partners: Partner;
    'miab-nominees': MiabNominee;
    'mining-orgs': MiningOrg;
    'map-locations': MapLocation;
    'meetup-submissions': MeetupSubmission;
    'course-signups': CourseSignup;
    'course-completions': CourseCompletion;
    'feedback-bounties': FeedbackBounty;
    vouchers: Voucher;
    'form-submissions': FormSubmission;
    redirects: Redirect;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    jobs: JobsSelect<false> | JobsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    'miab-nominees': MiabNomineesSelect<false> | MiabNomineesSelect<true>;
    'mining-orgs': MiningOrgsSelect<false> | MiningOrgsSelect<true>;
    'map-locations': MapLocationsSelect<false> | MapLocationsSelect<true>;
    'meetup-submissions': MeetupSubmissionsSelect<false> | MeetupSubmissionsSelect<true>;
    'course-signups': CourseSignupsSelect<false> | CourseSignupsSelect<true>;
    'course-completions': CourseCompletionsSelect<false> | CourseCompletionsSelect<true>;
    'feedback-bounties': FeedbackBountiesSelect<false> | FeedbackBountiesSelect<true>;
    vouchers: VouchersSelect<false> | VouchersSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    'site-settings': SiteSetting;
    'ac-settings': AcSetting;
    'gsheets-settings': GsheetsSetting;
    'admin-ops-log': AdminOpsLog;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'ac-settings': AcSettingsSelect<false> | AcSettingsSelect<true>;
    'gsheets-settings': GsheetsSettingsSelect<false> | GsheetsSettingsSelect<true>;
    'admin-ops-log': AdminOpsLogSelect<false> | AdminOpsLogSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Page builder blocks — add, reorder, and configure sections here.
   */
  content?:
    | (
        | HeroBlock
        | CardGridBlock
        | RichContentBlock
        | CTABannerBlock
        | StatsBarBlock
        | PartnersCarouselBlock
        | TestimonialsCarouselBlock
        | ProductsGridBlock
        | NewsletterSignupBlock
        | SupportSectionBlock
        | FormEmbedBlock
        | PricingTiersBlock
        | ProcessStepsBlock
        | PeopleShowcaseBlock
        | ReceiptWidgetBlock
        | MissionStatementsBlock
        | FlagsCarouselBlock
        | MiningDirectoryBlock
        | FeedbackMatrixBlock
        | CourseModalBlock
        | InflationSimulatorBlock
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  /**
   * Parent page — used to build breadcrumb hierarchy.
   */
  parent?: (number | null) | Page;
  template?:
    | ('default' | 'section-landing' | 'course' | 'partnership' | 'bounty' | 'mining' | 'miab' | 'proof-of-work')
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  layout?: ('text-left-image-right' | 'centered' | 'text-overlay') | null;
  /**
   * Small label above the heading (optional)
   */
  eyebrow?: string | null;
  /**
   * Optional link URL for the eyebrow label (e.g. https://bitcoinnews.africa/)
   */
  eyebrowUrl?: string | null;
  /**
   * Open eyebrow link in a new tab
   */
  eyebrowNewTab?: boolean | null;
  heading: string;
  subheading?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  backgroundType?: ('cream' | 'orange' | 'dark' | 'white' | 'image') | null;
  /**
   * Used when background type is "Image"
   */
  backgroundImage?: (number | null) | Media;
  images?:
    | {
        image: number | Media;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Short summary shown in archive listings.
   */
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  featuredImage?: (number | null) | Media;
  category?: ('weekly-newsletter' | 'saturday-stacker' | 'announcement') | null;
  publishedDate?: string | null;
  author?: (number | null) | User;
  /**
   * Raw HTML imported from WordPress. Replace with proper rich text content above when ready.
   */
  rawHtml?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role?: ('admin' | 'editor' | 'viewer') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardGridBlock".
 */
export interface CardGridBlock {
  eyebrow?: string | null;
  heading?: string | null;
  subheading?: string | null;
  columns?: ('2' | '3' | '4') | null;
  variant?: ('default' | 'orange-accent' | 'dark') | null;
  cards: {
    image?: (number | null) | Media;
    eyebrow?: string | null;
    title: string;
    description?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    linkLabel?: string | null;
    linkUrl?: string | null;
    linkNewTab?: boolean | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'cardGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichContentBlock".
 */
export interface RichContentBlock {
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Optional: image shown to the right of the content
   */
  sideImage?: (number | null) | Media;
  imagePosition?: ('right' | 'left') | null;
  backgroundColor?: ('white' | 'cream' | 'dark') | null;
  /**
   * Raw HTML imported from WordPress. Replace with proper rich text content above when ready.
   */
  rawHtml?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'richContent';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTABannerBlock".
 */
export interface CTABannerBlock {
  heading: string;
  subheading?: string | null;
  variant?: ('orange' | 'dark' | 'light') | null;
  primaryButtonLabel?: string | null;
  primaryButtonUrl?: string | null;
  secondaryButtonLabel?: string | null;
  secondaryButtonUrl?: string | null;
  align?: ('center' | 'left') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ctaBanner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBarBlock".
 */
export interface StatsBarBlock {
  backgroundColor?: ('dark' | 'orange' | 'white' | 'cream') | null;
  stats: {
    /**
     * e.g. "10K+"
     */
    value: string;
    /**
     * e.g. "Community Members"
     */
    label: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'statsBar';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PartnersCarouselBlock".
 */
export interface PartnersCarouselBlock {
  /**
   * Small label above the logos (optional)
   */
  heading?: string | null;
  useGlobalPartners?: boolean | null;
  /**
   * Manual list of partners to display
   */
  partners?:
    | {
        name: string;
        logoImage?: (number | null) | Media;
        websiteURL?: string | null;
        id?: string | null;
      }[]
    | null;
  speed?: ('slow' | 'normal' | 'fast') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'partnersCarousel';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsCarouselBlock".
 */
export interface TestimonialsCarouselBlock {
  eyebrow?: string | null;
  heading?: string | null;
  useGlobalTestimonials?: boolean | null;
  testimonials?:
    | {
        text: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        name: string;
        role?: string | null;
        avatarColor?: string | null;
        /**
         * 1-2 characters
         */
        initial?: string | null;
        id?: string | null;
      }[]
    | null;
  backgroundColor?: ('cream' | 'white' | 'dark') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonialsCarousel';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProductsGridBlock".
 */
export interface ProductsGridBlock {
  eyebrow?: string | null;
  heading?: string | null;
  subheading?: string | null;
  products: {
    name: string;
    tagline?: string | null;
    description?: string | null;
    mockupImage?: (number | null) | Media;
    /**
     * e.g. "Free", "New", "Coming Soon"
     */
    badge?: string | null;
    primaryButtonLabel?: string | null;
    primaryButtonUrl?: string | null;
    secondaryButtonLabel?: string | null;
    secondaryButtonUrl?: string | null;
    features?:
      | {
          feature: string;
          id?: string | null;
        }[]
      | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'productsGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NewsletterSignupBlock".
 */
export interface NewsletterSignupBlock {
  heading?: string | null;
  subheading?: string | null;
  buttonLabel?: string | null;
  backgroundColor?: ('dark' | 'orange' | 'cream' | 'white') | null;
  successMessage?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'newsletterSignup';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SupportSectionBlock".
 */
export interface SupportSectionBlock {
  eyebrow?: string | null;
  heading: string;
  description?: string | null;
  bulletPoints?:
    | {
        point: string;
        id?: string | null;
      }[]
    | null;
  primaryButtonLabel?: string | null;
  primaryButtonUrl?: string | null;
  secondaryButtonLabel?: string | null;
  secondaryButtonUrl?: string | null;
  qrCodeImage?: (number | null) | Media;
  /**
   * e.g. "Scan to donate Bitcoin"
   */
  qrCaption?: string | null;
  backgroundColor?: ('cream' | 'dark' | 'white') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'supportSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormEmbedBlock".
 */
export interface FormEmbedBlock {
  /**
   * Select which form to display on this page section
   */
  formType:
    | 'idea-submission'
    | 'project-application'
    | 'bootcamp-enrollment'
    | 'merchandise-order'
    | 'community-membership'
    | 'event-rsvp'
    | 'speaker-application'
    | 'partnership-inquiry'
    | 'donation'
    | 'contact-general'
    | 'feedback-rating'
    | 'mining-directory'
    | 'payload-form';
  /**
   * Optional heading above the form
   */
  heading?: string | null;
  subheading?: string | null;
  backgroundColor?: ('white' | 'cream') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formEmbed';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PricingTiersBlock".
 */
export interface PricingTiersBlock {
  eyebrow?: string | null;
  heading?: string | null;
  subheading?: string | null;
  currency?: ('sats' | 'usd' | 'eur') | null;
  tiers: {
    name: string;
    monthlyPrice: number;
    yearlyPrice: number;
    description?: string | null;
    features?:
      | {
          feature: string;
          included?: boolean | null;
          id?: string | null;
        }[]
      | null;
    buttonText?: string | null;
    buttonLink?: string | null;
    isHighlighted?: boolean | null;
    /**
     * e.g. "Most Popular", "Best Value"
     */
    badge?: string | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'pricingTiers';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProcessStepsBlock".
 */
export interface ProcessStepsBlock {
  eyebrow?: string | null;
  heading?: string | null;
  subheading?: string | null;
  variant?: ('numbered' | 'horizontal') | null;
  backgroundColor?: ('cream' | 'white' | 'dark') | null;
  steps: {
    number: number;
    title: string;
    description?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    linkText?: string | null;
    linkURL?: string | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'processSteps';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PeopleShowcaseBlock".
 */
export interface PeopleShowcaseBlock {
  /**
   * MIAB year to display
   */
  year: number;
  heading?: string | null;
  layout?: ('grid-2col' | 'list-alternating') | null;
  showYearNav?: boolean | null;
  otherYears?:
    | {
        year: number;
        url: string;
        id?: string | null;
      }[]
    | null;
  backgroundColor?: ('cream' | 'white' | 'dark') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'peopleShowcase';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ReceiptWidgetBlock".
 */
export interface ReceiptWidgetBlock {
  title?: string | null;
  metrics: {
    label: string;
    value: string;
    id?: string | null;
  }[];
  totalLabel?: string | null;
  totalValue?: string | null;
  footerText?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'receiptWidget';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MissionStatementsBlock".
 */
export interface MissionStatementsBlock {
  statements: {
    eyebrow?: string | null;
    /**
     * Use bold/italic to highlight key words in orange
     */
    heading: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    backgroundImage?: (number | null) | Media;
    textColor?: ('dark' | 'white' | 'orange') | null;
    id?: string | null;
  }[];
  spacing?: ('large' | 'medium' | 'compact') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'missionStatements';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FlagsCarouselBlock".
 */
export interface FlagsCarouselBlock {
  heading?: string | null;
  countries: {
    name: string;
    /**
     * Used in URL: /top-african-bitcoin-countries-{slug}/
     */
    slug: string;
    /**
     * ISO 3166-1 alpha-2 (e.g. NG, ZA, KE)
     */
    countryCode: string;
    id?: string | null;
  }[];
  speed?: ('slow' | 'normal' | 'fast') | null;
  backgroundColor?: ('cream' | 'white' | 'dark') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'flagsCarousel';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MiningDirectoryBlock".
 */
export interface MiningDirectoryBlock {
  heading?: string | null;
  subheading?: string | null;
  groupByCountry?: boolean | null;
  showAddListingButton?: boolean | null;
  addListingUrl?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'miningDirectory';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeedbackMatrixBlock".
 */
export interface FeedbackMatrixBlock {
  heading?: string | null;
  subheading?: string | null;
  showSearch?: boolean | null;
  /**
   * Reward shown in the heading (e.g. "1,000 sats")
   */
  rewardPerItem?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'feedbackMatrix';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CourseModalBlock".
 */
export interface CourseModalBlock {
  triggerLabel?: string | null;
  variant?: ('primary-orange' | 'white-outline' | 'dark-blue') | null;
  /**
   * English email signup URL
   */
  emailSignupUrl?: string | null;
  /**
   * French email signup URL
   */
  emailSignupUrlFr?: string | null;
  /**
   * Telegram group/channel URL
   */
  telegramUrl?: string | null;
  /**
   * French Telegram URL
   */
  telegramUrlFr?: string | null;
  websiteUrl?: string | null;
  layout?: ('inline' | 'modal') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'courseModal';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InflationSimulatorBlock".
 */
export interface InflationSimulatorBlock {
  heading?: string | null;
  subheading?: string | null;
  /**
   * Default currency code to pre-select (e.g. NGN, ZAR, KES)
   */
  defaultCurrency?: string | null;
  defaultAmount?: number | null;
  defaultYearsAgo?: number | null;
  backgroundColor?: ('cream' | 'dark' | 'white') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'inflationSimulator';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs".
 */
export interface Job {
  id: number;
  title: string;
  company: string;
  companyDescription?: string | null;
  websiteURL?: string | null;
  location?: string | null;
  type?: ('full-time' | 'part-time' | 'contract' | 'volunteer') | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  contactEmail?: string | null;
  contactName?: string | null;
  isActive?: boolean | null;
  postedDate?: string | null;
  /**
   * ID used by social share script.
   */
  shareButtonId?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  text: string;
  name: string;
  /**
   * Single character shown in the avatar circle.
   */
  initial?: string | null;
  /**
   * Hex color code for the avatar background (e.g. #FD5A47).
   */
  avatarColor?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  name: string;
  logoImage: number | Media;
  websiteURL?: string | null;
  /**
   * Display width in pixels for the partner logo in the carousel.
   */
  logoWidth?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "miab-nominees".
 */
export interface MiabNominee {
  id: number;
  year: number;
  rank: number;
  name: string;
  country?: string | null;
  countryFlagEmoji?: string | null;
  photo?: (number | null) | Media;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  socialLinks?:
    | {
        platform: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  isPublished?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mining-orgs".
 */
export interface MiningOrg {
  id: number;
  name: string;
  country?: string | null;
  /**
   * ISO 3166-1 alpha-2 country code (e.g. NG, ZA, KE).
   */
  countryFlagCode?: string | null;
  city?: string | null;
  description?: string | null;
  founderName?: string | null;
  contactPerson?: string | null;
  contactEmail?: string | null;
  websiteURL?: string | null;
  twitterURL?: string | null;
  logoImage?: (number | null) | Media;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "map-locations".
 */
export interface MapLocation {
  id: number;
  merchantName: string;
  description?: string | null;
  websiteURL?: string | null;
  address?: string | null;
  email?: string | null;
  phone?: string | null;
  acceptsLightning?: boolean | null;
  category?: ('merchant' | 'service' | 'atm') | null;
  latitude?: number | null;
  longitude?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "meetup-submissions".
 */
export interface MeetupSubmission {
  id: number;
  meetupName: string;
  description?: string | null;
  location?: string | null;
  startDate?: string | null;
  endDate?: string | null;
  time?: string | null;
  contactName?: string | null;
  contactEmail?: string | null;
  flyerImage?: (number | null) | Media;
  status?: ('pending' | 'approved' | 'rejected') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-signups".
 */
export interface CourseSignup {
  id: number;
  name: string;
  email?: string | null;
  country?: string | null;
  /**
   * 7-character alphanumeric code generated at signup.
   */
  uniqueCode?: string | null;
  utmCampaign?: string | null;
  tierLevel?: ('ba' | 'ad' | 'pr') | null;
  courseLang: 'English' | 'French';
  deliveryMethod: 'email' | 'telegram';
  ipAddress?: string | null;
  signupDate?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-completions".
 */
export interface CourseCompletion {
  id: number;
  name: string;
  email?: string | null;
  score?: number | null;
  scorePercent?: number | null;
  /**
   * Auto-generated certificate number (BC000001+). Do not edit manually.
   */
  certNumber?: string | null;
  certHash?: string | null;
  uniqueCode?: string | null;
  courseLang?: ('English' | 'French') | null;
  tierLevel?: ('ba' | 'ad' | 'pr') | null;
  utmCampaign?: string | null;
  certDownloaded?: boolean | null;
  downloadCount?: number | null;
  tbtDiscountSent?: boolean | null;
  completionDate?: string | null;
  ipAddress?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Community feedback submissions. Change "Status" to trigger automated emails and voucher assignment.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedback-bounties".
 */
export interface FeedbackBounty {
  id: number;
  name: string;
  email?: string | null;
  feedbackTitle: string;
  category?: ('Course Content' | 'Course Delivery' | 'Website' | 'Network/Community' | 'Suggestion') | null;
  description?: string | null;
  /**
   * Has this feedback been submitted before?
   */
  feedbackBefore?: ('yes' | 'no') | null;
  /**
   * Changing this triggers automated email and reward assignment.
   */
  status?: ('Pending' | 'Under review' | 'Accepted' | 'Not accepted' | 'Idea' | 'Implemented') | null;
  /**
   * Auto-managed by status changes.
   */
  rewardStatus?: ('Pending' | 'Processing' | 'Paid' | 'Not paid') | null;
  /**
   * Auto-set when status changes to Implemented.
   */
  implementationDate?: string | null;
  /**
   * Auto-updated on any status change.
   */
  lastActivity?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * LNURL voucher codes for the 1000 Sats Feedback Bounty reward.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vouchers".
 */
export interface Voucher {
  id: number;
  voucherCode: string;
  /**
   * Email address the voucher was sent to.
   */
  sentTo?: string | null;
  sentDate?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Generic store for all public form submissions (replaces Gravity Forms entries).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  formName: string;
  formSlug?: string | null;
  /**
   * Raw form field data as JSON.
   */
  data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  submittedAt?: string | null;
  ipAddress?: string | null;
  status?: ('active' | 'spam' | 'trash') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'posts';
    value: number | Post;
  };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'jobs';
        value: number | Job;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'miab-nominees';
        value: number | MiabNominee;
      } | null)
    | ({
        relationTo: 'mining-orgs';
        value: number | MiningOrg;
      } | null)
    | ({
        relationTo: 'map-locations';
        value: number | MapLocation;
      } | null)
    | ({
        relationTo: 'meetup-submissions';
        value: number | MeetupSubmission;
      } | null)
    | ({
        relationTo: 'course-signups';
        value: number | CourseSignup;
      } | null)
    | ({
        relationTo: 'course-completions';
        value: number | CourseCompletion;
      } | null)
    | ({
        relationTo: 'feedback-bounties';
        value: number | FeedbackBounty;
      } | null)
    | ({
        relationTo: 'vouchers';
        value: number | Voucher;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  content?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        cardGrid?: T | CardGridBlockSelect<T>;
        richContent?: T | RichContentBlockSelect<T>;
        ctaBanner?: T | CTABannerBlockSelect<T>;
        statsBar?: T | StatsBarBlockSelect<T>;
        partnersCarousel?: T | PartnersCarouselBlockSelect<T>;
        testimonialsCarousel?: T | TestimonialsCarouselBlockSelect<T>;
        productsGrid?: T | ProductsGridBlockSelect<T>;
        newsletterSignup?: T | NewsletterSignupBlockSelect<T>;
        supportSection?: T | SupportSectionBlockSelect<T>;
        formEmbed?: T | FormEmbedBlockSelect<T>;
        pricingTiers?: T | PricingTiersBlockSelect<T>;
        processSteps?: T | ProcessStepsBlockSelect<T>;
        peopleShowcase?: T | PeopleShowcaseBlockSelect<T>;
        receiptWidget?: T | ReceiptWidgetBlockSelect<T>;
        missionStatements?: T | MissionStatementsBlockSelect<T>;
        flagsCarousel?: T | FlagsCarouselBlockSelect<T>;
        miningDirectory?: T | MiningDirectoryBlockSelect<T>;
        feedbackMatrix?: T | FeedbackMatrixBlockSelect<T>;
        courseModal?: T | CourseModalBlockSelect<T>;
        inflationSimulator?: T | InflationSimulatorBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  parent?: T;
  template?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  layout?: T;
  eyebrow?: T;
  eyebrowUrl?: T;
  eyebrowNewTab?: T;
  heading?: T;
  subheading?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  backgroundType?: T;
  backgroundImage?: T;
  images?:
    | T
    | {
        image?: T;
        alt?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardGridBlock_select".
 */
export interface CardGridBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  subheading?: T;
  columns?: T;
  variant?: T;
  cards?:
    | T
    | {
        image?: T;
        eyebrow?: T;
        title?: T;
        description?: T;
        linkLabel?: T;
        linkUrl?: T;
        linkNewTab?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichContentBlock_select".
 */
export interface RichContentBlockSelect<T extends boolean = true> {
  content?: T;
  sideImage?: T;
  imagePosition?: T;
  backgroundColor?: T;
  rawHtml?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTABannerBlock_select".
 */
export interface CTABannerBlockSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  variant?: T;
  primaryButtonLabel?: T;
  primaryButtonUrl?: T;
  secondaryButtonLabel?: T;
  secondaryButtonUrl?: T;
  align?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBarBlock_select".
 */
export interface StatsBarBlockSelect<T extends boolean = true> {
  backgroundColor?: T;
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PartnersCarouselBlock_select".
 */
export interface PartnersCarouselBlockSelect<T extends boolean = true> {
  heading?: T;
  useGlobalPartners?: T;
  partners?:
    | T
    | {
        name?: T;
        logoImage?: T;
        websiteURL?: T;
        id?: T;
      };
  speed?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsCarouselBlock_select".
 */
export interface TestimonialsCarouselBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  useGlobalTestimonials?: T;
  testimonials?:
    | T
    | {
        text?: T;
        name?: T;
        role?: T;
        avatarColor?: T;
        initial?: T;
        id?: T;
      };
  backgroundColor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProductsGridBlock_select".
 */
export interface ProductsGridBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  subheading?: T;
  products?:
    | T
    | {
        name?: T;
        tagline?: T;
        description?: T;
        mockupImage?: T;
        badge?: T;
        primaryButtonLabel?: T;
        primaryButtonUrl?: T;
        secondaryButtonLabel?: T;
        secondaryButtonUrl?: T;
        features?:
          | T
          | {
              feature?: T;
              id?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NewsletterSignupBlock_select".
 */
export interface NewsletterSignupBlockSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  buttonLabel?: T;
  backgroundColor?: T;
  successMessage?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SupportSectionBlock_select".
 */
export interface SupportSectionBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  description?: T;
  bulletPoints?:
    | T
    | {
        point?: T;
        id?: T;
      };
  primaryButtonLabel?: T;
  primaryButtonUrl?: T;
  secondaryButtonLabel?: T;
  secondaryButtonUrl?: T;
  qrCodeImage?: T;
  qrCaption?: T;
  backgroundColor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormEmbedBlock_select".
 */
export interface FormEmbedBlockSelect<T extends boolean = true> {
  formType?: T;
  heading?: T;
  subheading?: T;
  backgroundColor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PricingTiersBlock_select".
 */
export interface PricingTiersBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  subheading?: T;
  currency?: T;
  tiers?:
    | T
    | {
        name?: T;
        monthlyPrice?: T;
        yearlyPrice?: T;
        description?: T;
        features?:
          | T
          | {
              feature?: T;
              included?: T;
              id?: T;
            };
        buttonText?: T;
        buttonLink?: T;
        isHighlighted?: T;
        badge?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProcessStepsBlock_select".
 */
export interface ProcessStepsBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  subheading?: T;
  variant?: T;
  backgroundColor?: T;
  steps?:
    | T
    | {
        number?: T;
        title?: T;
        description?: T;
        linkText?: T;
        linkURL?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PeopleShowcaseBlock_select".
 */
export interface PeopleShowcaseBlockSelect<T extends boolean = true> {
  year?: T;
  heading?: T;
  layout?: T;
  showYearNav?: T;
  otherYears?:
    | T
    | {
        year?: T;
        url?: T;
        id?: T;
      };
  backgroundColor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ReceiptWidgetBlock_select".
 */
export interface ReceiptWidgetBlockSelect<T extends boolean = true> {
  title?: T;
  metrics?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  totalLabel?: T;
  totalValue?: T;
  footerText?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MissionStatementsBlock_select".
 */
export interface MissionStatementsBlockSelect<T extends boolean = true> {
  statements?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        backgroundImage?: T;
        textColor?: T;
        id?: T;
      };
  spacing?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FlagsCarouselBlock_select".
 */
export interface FlagsCarouselBlockSelect<T extends boolean = true> {
  heading?: T;
  countries?:
    | T
    | {
        name?: T;
        slug?: T;
        countryCode?: T;
        id?: T;
      };
  speed?: T;
  backgroundColor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MiningDirectoryBlock_select".
 */
export interface MiningDirectoryBlockSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  groupByCountry?: T;
  showAddListingButton?: T;
  addListingUrl?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeedbackMatrixBlock_select".
 */
export interface FeedbackMatrixBlockSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  showSearch?: T;
  rewardPerItem?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CourseModalBlock_select".
 */
export interface CourseModalBlockSelect<T extends boolean = true> {
  triggerLabel?: T;
  variant?: T;
  emailSignupUrl?: T;
  emailSignupUrlFr?: T;
  telegramUrl?: T;
  telegramUrlFr?: T;
  websiteUrl?: T;
  layout?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InflationSimulatorBlock_select".
 */
export interface InflationSimulatorBlockSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  defaultCurrency?: T;
  defaultAmount?: T;
  defaultYearsAgo?: T;
  backgroundColor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  content?: T;
  featuredImage?: T;
  category?: T;
  publishedDate?: T;
  author?: T;
  rawHtml?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs_select".
 */
export interface JobsSelect<T extends boolean = true> {
  title?: T;
  company?: T;
  companyDescription?: T;
  websiteURL?: T;
  location?: T;
  type?: T;
  description?: T;
  contactEmail?: T;
  contactName?: T;
  isActive?: T;
  postedDate?: T;
  shareButtonId?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  text?: T;
  name?: T;
  initial?: T;
  avatarColor?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  logoImage?: T;
  websiteURL?: T;
  logoWidth?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "miab-nominees_select".
 */
export interface MiabNomineesSelect<T extends boolean = true> {
  year?: T;
  rank?: T;
  name?: T;
  country?: T;
  countryFlagEmoji?: T;
  photo?: T;
  bio?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  isPublished?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mining-orgs_select".
 */
export interface MiningOrgsSelect<T extends boolean = true> {
  name?: T;
  country?: T;
  countryFlagCode?: T;
  city?: T;
  description?: T;
  founderName?: T;
  contactPerson?: T;
  contactEmail?: T;
  websiteURL?: T;
  twitterURL?: T;
  logoImage?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "map-locations_select".
 */
export interface MapLocationsSelect<T extends boolean = true> {
  merchantName?: T;
  description?: T;
  websiteURL?: T;
  address?: T;
  email?: T;
  phone?: T;
  acceptsLightning?: T;
  category?: T;
  latitude?: T;
  longitude?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "meetup-submissions_select".
 */
export interface MeetupSubmissionsSelect<T extends boolean = true> {
  meetupName?: T;
  description?: T;
  location?: T;
  startDate?: T;
  endDate?: T;
  time?: T;
  contactName?: T;
  contactEmail?: T;
  flyerImage?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-signups_select".
 */
export interface CourseSignupsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  country?: T;
  uniqueCode?: T;
  utmCampaign?: T;
  tierLevel?: T;
  courseLang?: T;
  deliveryMethod?: T;
  ipAddress?: T;
  signupDate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-completions_select".
 */
export interface CourseCompletionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  score?: T;
  scorePercent?: T;
  certNumber?: T;
  certHash?: T;
  uniqueCode?: T;
  courseLang?: T;
  tierLevel?: T;
  utmCampaign?: T;
  certDownloaded?: T;
  downloadCount?: T;
  tbtDiscountSent?: T;
  completionDate?: T;
  ipAddress?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedback-bounties_select".
 */
export interface FeedbackBountiesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  feedbackTitle?: T;
  category?: T;
  description?: T;
  feedbackBefore?: T;
  status?: T;
  rewardStatus?: T;
  implementationDate?: T;
  lastActivity?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vouchers_select".
 */
export interface VouchersSelect<T extends boolean = true> {
  voucherCode?: T;
  sentTo?: T;
  sentDate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  formName?: T;
  formSlug?: T;
  data?: T;
  submittedAt?: T;
  ipAddress?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        label: string;
        type: 'link' | 'dropdown';
        /**
         * URL for single link items
         */
        url?: string | null;
        children?:
          | {
              label: string;
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  description?: string | null;
  /**
   * Main footer navigation links
   */
  quickLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Footer bottom row links (Privacy Policy, Terms, etc.)
   */
  utilityLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  copyrightText?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  tagline?: string | null;
  siteDescription?: string | null;
  logo?: (number | null) | Media;
  favicon?: (number | null) | Media;
  socialLinks?:
    | {
        platform:
          | 'whatsapp'
          | 'twitter'
          | 'instagram'
          | 'facebook'
          | 'linkedin'
          | 'telegram'
          | 'discord'
          | 'nostr'
          | 'youtube';
        url: string;
        id?: string | null;
      }[]
    | null;
  donationQRImage?: (number | null) | Media;
  donationBTCPayLink?: string | null;
  chatbot?: {
    chatbotEnabled?: boolean | null;
    chatbotApiUrl?: string | null;
    chatbotLogUrl?: string | null;
  };
  analytics?: {
    analyticsEnabled?: boolean | null;
    /**
     * e.g. GTM-P3M4DLWQ
     */
    gtmId?: string | null;
    /**
     * e.g. G-XXXXXXXXXX
     */
    ga4Id?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Map each form submission type to an ActiveCampaign list. Every contact is also added to the "master" list regardless of which form they use.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ac-settings".
 */
export interface AcSetting {
  id: number;
  /**
   * Each row maps a form submission type to an exact ActiveCampaign list name. The "master" entry defines the secondary list every contact is always added to.
   */
  listMappings?:
    | {
        /**
         * Which form triggers this sync
         */
        formSlug:
          | 'newsletter-signup'
          | 'education-partnership'
          | 'course-signup-english'
          | 'course-signup-french'
          | 'final-quiz-passed'
          | 'final-quiz-failed'
          | 'savings-challenge'
          | 'contact'
          | 'master';
        /**
         * Exact ActiveCampaign list name (case-sensitive — use "Fetch Lists" above to verify)
         */
        listName: string;
        enabled?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Map each form type to a Google Sheet. EM will fill in the spreadsheet IDs once the sheets are ready. Leave empty to disable Sheets sync for that form.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gsheets-settings".
 */
export interface GsheetsSetting {
  id: number;
  sheetMappings?:
    | {
        /**
         * Form identifier (e.g. feedback-bounty, bfb-day-1-feedback, nps-general, volunteers, graduate-programme)
         */
        formSlug: string;
        /**
         * Google Sheet ID — the long alphanumeric part of the sheet URL
         */
        spreadsheetId: string;
        /**
         * Tab name within the spreadsheet (usually "Sheet1")
         */
        sheetName?: string | null;
        enabled?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin-ops-log".
 */
export interface AdminOpsLog {
  id: number;
  entries?:
    | {
        timestamp?: string | null;
        action: string;
        collection?: string | null;
        details?: string | null;
        user?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        label?: T;
        type?: T;
        url?: T;
        children?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  description?: T;
  quickLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  utilityLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  copyrightText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  siteDescription?: T;
  logo?: T;
  favicon?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  donationQRImage?: T;
  donationBTCPayLink?: T;
  chatbot?:
    | T
    | {
        chatbotEnabled?: T;
        chatbotApiUrl?: T;
        chatbotLogUrl?: T;
      };
  analytics?:
    | T
    | {
        analyticsEnabled?: T;
        gtmId?: T;
        ga4Id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ac-settings_select".
 */
export interface AcSettingsSelect<T extends boolean = true> {
  listMappings?:
    | T
    | {
        formSlug?: T;
        listName?: T;
        enabled?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gsheets-settings_select".
 */
export interface GsheetsSettingsSelect<T extends boolean = true> {
  sheetMappings?:
    | T
    | {
        formSlug?: T;
        spreadsheetId?: T;
        sheetName?: T;
        enabled?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin-ops-log_select".
 */
export interface AdminOpsLogSelect<T extends boolean = true> {
  entries?:
    | T
    | {
        timestamp?: T;
        action?: T;
        collection?: T;
        details?: T;
        user?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}