const R2 = 'https://pub-d2aef463d8a6497d90ac252cbcb0dcbf.r2.dev'

export const IMG = {
  hero: `${R2}/uploads/2024/03/African-Bitcoiners_About-Us-Page-hero-image.png`,
  visionIcon: `${R2}/uploads/2023/12/Our-Vision-Icon.png`,
  visionImage: `${R2}/uploads/2024/03/African-Bitcoiners_Our-Vision-Image.png`,
  goalIcon: `${R2}/uploads/2023/12/Our-Crazy-Goal-Icon.png`,
  goalImage: `${R2}/uploads/2024/03/African-Bitcoiners_Our-Crazy-Goal-Image.png`,
  teamIcon: `${R2}/uploads/2023/12/Our-Crazy-Goal-Icon.png`,
  teamImage: `${R2}/uploads/2024/04/African_Bitcoiners_Generic_Partnership_page_image1-920x1024.png`,
  vectorEye: `${R2}/uploads/2023/12/About-us-page-vector.png`,
  vectorTarget: `${R2}/uploads/2023/12/About-us-page-vector-2.png`,
} as const

export const HERO_HTML =
  'We are a Bitcoin community helping to onboard new African users and guide them safely on their Bitcoin journey from earning sats to self custody. We try and pay our bills through sponsorships and by building out Bitcoin services which add value to our community members. Most notably, we offer a free Bitcoin for Beginners course and our services include <a href="https://freerouting.africa/" target="_blank" rel="noopener">Africa Free Routing</a>, <a href="https://bitcoinertest.com/" target="_blank" rel="noopener">The Bitcoiner Test</a> and <a href="https://sats2data.africa/" target="_blank" rel="noopener">Sats2Data</a>.'

export const VALUES = [
  {
    title: 'Accountability',
    body: 'We are dependable. We make sure our tasks and objectives are delivered on time every time and at the highest quality. We communicate about roadblocks well in advance. African Bitcoiners will bring Freedom to Africa through Bitcoin.',
    bg: `${R2}/uploads/2023/12/Accountability-Value-background.png`,
    className: 'md:mr-3 md:-mt-0',
    titlePad: 'pt-[70px] md:pt-[70px]',
  },
  {
    title: 'Truth Seeking',
    body: 'We are open minded and evidence-based. We strive to be objective and facts focussed and constantly challenge group think and the “status quo” in pursuit of the underlying truth. We make decisions from hard data wherever possible and are mindful of our cognitive biases.',
    bg: `${R2}/uploads/2023/12/Truth-Seeking-Value-background.png`,
    className: 'md:ml-3',
    titlePad: 'pt-[70px] md:pt-[70px]',
  },
  {
    title: 'Kindness',
    body: 'We are trustworthy, humble, fun to work with and sincerely want the utmost success for each other and our community. We always treat each other and our community with kindness and respect.',
    bg: `${R2}/uploads/2023/12/Kindness-Value-background.png`,
    className: 'md:-mt-[60px] md:mr-4',
    titlePad: 'pt-[90px] md:pt-[90px]',
  },
  {
    title: 'Growth Mindset',
    body: 'We believe that with hard work and relentless curiousity we can achieve anything. We are always reading, testing, learning and improving. We move forward with urgency making fast decisions and continuously learning from our many failures.',
    bg: `${R2}/uploads/2023/12/Growth-Mindset-Value-background.png`,
    className: 'md:mt-5 md:mx-2',
    titlePad: 'pt-[70px] md:pt-[70px]',
  },
  {
    title: 'Privacy',
    body: 'We are leaders of a peaceful revolution. This comes with risks particularly when the inevitable state backlash comes against Bitcoin. To protect themselves and their loved ones, many of our team prefer to remain pseudonymous and so we always operate with their privacy front of mind.',
    bg: `${R2}/uploads/2023/12/Privacy-Value-background.png`,
    className: 'md:-mt-[60px] md:ml-4',
    titlePad: 'pt-[60px] md:pt-[60px]',
  },
] as const

export const COUNTRIES = [
  'Algeria',
  'Angola',
  'Benin',
  'Botswana',
  'Burkina Faso',
  'Burundi',
  'Cabo Verde',
  'Cameroon',
  'Central African Republic',
  'Chad',
  'Comoros',
  'Congo, Democratic Republic of the',
  'Congo, Republic of the',
  "Cote d'Ivoire",
  'Djibouti',
  'Egypt',
  'Equatorial Guinea',
  'Eritrea',
  'Eswatini',
  'Ethiopia',
  'Gabon',
  'Gambia',
  'Ghana',
  'Guinea',
  'Guinea-Bissau',
  'Kenya',
  'Lesotho',
  'Liberia',
  'Libya',
  'Madagascar',
  'Malawi',
  'Mali',
  'Mauritania',
  'Mauritius',
  'Morocco',
  'Mozambique',
  'Namibia',
  'Niger',
  'Nigeria',
  'Rwanda',
  'Sao Tome and Principe',
  'Senegal',
  'Seychelles',
  'Sierra Leone',
  'Somalia',
  'South Africa',
  'South Sudan',
  'Sudan',
  'Tanzania',
  'Togo',
  'Tunisia',
  'Uganda',
  'Zambia',
  'Zimbabwe',
  'Africa',
  'Antarctica',
  'Asia',
  'Australia',
  'Europe',
  'North America',
  'South America',
] as const
